### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by lbolla** [lastquestion/explain-pause-mode#1]
The README (https://github.com/lastquestion/explain-pause-mode/blob/master/README.md#L5-L5) reads to use `(require-pause-mode t)`, but that command doesn't exist. Instead, it should read: `(explain-pause-mode t)`.

**Comment by lastquestion** [comment]
![hiding homer](https://media.giphy.com/media/YSeRKAa0JJjTJxbD0R/giphy-downsized.gif)

LOL, woops. Thanks for catching that.
