### ISSUE TITLE
Drop `dash.el` dependency

### ISSUE THREAD

**Issue by lastquestion** [lastquestion/explain-pause-mode#12]
- [ ] `dash.el` - It's really only used for `-let` and a few other things, and depending only on emacs builtins would make packaging and testing this easier.

~- [ ] Check https://github.com/alphapapa/emacs-package-dev-handbook for other useful things~ I'll open new issues as I explore more and keep this one simple

**Comment by JiaHong-Lee** [comment]
`pcase-let` could be used as a good alternative to `-let`. See: [alphapapa’s comment on Reddit](https://www.reddit.com/r/emacs/comments/gmh8bs/beta_testers_ann_lets_make_emacs_better/fr70cu3/)

**Comment by lastquestion** [comment]
@alphapapa, sorry for tagging on GH without asking. I started reading https://github.com/alphapapa/emacs-package-dev-handbook#pattern-matching and it's **GREAT**. Awesome. Thanks for making it and collecting all that info.
