### ISSUE TITLE
`top` for commands 

### ISSUE THREAD

**Issue by lastquestion** [lastquestion/explain-pause-mode#4]
*note: edited with spec from original ideas when first opened (hit edited for a dropdown of change history in github)*

**Make a table of the top N commands, that works like `top`**

* columns:
  * command
  * avg-ms
  * total ms
  * invocations
* sortable

Call it `explain-pause-top`. Should be a major mode.

* make it fast enough to refresh automatically. Controllable refresh interval.
* Data is collected for lifetime of emacs, can be user cleared

First PR should do the above. Next new issues:

* Handle actions and remove `explain-top-report` (profile, select for profile, ignore for profile, etc.)
* Add keymaps, faces
* clean up the internal routing and use same system for logging
* Support trees for command-sets, original buffer

**Comment by lastquestion** [comment]
This idea came from https://www.reddit.com/r/emacs/comments/gmh8bs/beta_testers_ann_lets_make_emacs_better/fr3u836/, thanks to "/u/celeritasCelery"

**Comment by jimeh** [comment]
May I suggest `g` to refresh? Just like dired, magit, and others already do :)

**Comment by lastquestion** [comment]
Uh, that makes perfect sense. :+1: let's do that.

**Comment by mpereira** [comment]
+1 on the idea of binding `g` to refresh. @lastquestion are you thinking of making that buffer have a special minor mode so that one could also create arbitrary keybindings for it? For example, as an Evil user, it would be handy if I could bind `q` to `evil-quit`, which kills the buffer.

**Comment by lastquestion** [comment]
I tried very hard to use the mode `tabulated-list` which is shipped in emacs itself, as a derived major mode. I gave up because it's not very flexible, and it's not that performant. 

This will be a major mode `Explain-Pause-Top` which you can bind keymaps for, yeah. 

There'll be faces that can be customized, for now: 
* "slow" (red)

The refresh interval is custom, I tried to use `auto-revert-buffers` but it only has one custom interval that applies to all buffers it tries to revert. 

I'm going to try and get the blocking render to under 20ms and then I'll be OK with having the default behavior be "autorefresh every 2 (?) seconds".

I will update the description with my decisions so far once I get a PR out.

**Comment by mpereira** [comment]
It's probably unrelated to this issue, but it would also be nice to have a mode for the `explain-pause-log` buffer for the same reason.

**Comment by lastquestion** [comment]
> It's probably unrelated to this issue, but it would also be nice to have a mode for the explain-pause-log buffer for the same reason.
Yes, feel free to open an issue, I have some ideas for improving that log stream. It needs faces, tail correctly, stay in place if you move off the tail, etc. Having a mode for that buffer is needed for those things anyway :+1:

**Comment by lastquestion** [comment]
Update on current status:
<img width="672" alt="Screen Shot 2020-05-24 at 1 22 25 PM" src="https://user-images.githubusercontent.com/1095956/82764387-20a3a300-9dc3-11ea-8fdd-092237d4898d.png">

There are a few things I need to do before pushing the first PR:

- [ ] Make avg fixed 2 float `x.xx` 
- [ ] Fix up code that does fixed column sizing
- [ ] Add one space for padding between columns
- [ ] Print commands on multiple lines instead of truncating

Hopefully should have something later this week.

**Comment by lastquestion** [comment]
#23 implements all of the original idea, but I'll leave this issue open until I update the README and documentation in follow up PRs.

**Comment by lastquestion** [comment]
Meh, github has decided it wants to close this. I'm fine with it, 😆
