### ISSUE TITLE
87b0478 breaks emacs if started during init

### ISSUE THREAD

**Issue by aaronjensen** [lastquestion/explain-pause-mode#75]
Prior to this, it worked fine on Emacs 27 with my config. With the latest master, I see this or something like it after every command and nothing works at all. I have to kill emacs.

```
*ERROR*: Symbol’s function definition is void: explain-pause--seq-contains
```

As far as I can tell, if I start emacs and then evaluate explain-pause-mode, it works out.

**Comment by lastquestion** [comment]
Argh, this is totally because when I bytecompile and then test I... didn't actually load the bytecompiled file. I will fix that in the makefile.

I'm inept.

So sorry, getting a fix together now...

**Comment by lastquestion** [comment]
I fixed this, and I fixed it so I actually test byte-compiled in the test suite so this kind of thing shouldn't happen again. Appreciate you taking the time to file a bug and sorry for the interruption, you have to kill emacs to get out of that error loop, it's really sucky.

**Comment by bqv** [comment]
Actually I got out of it via emacsclient --eval, but yes. Thanks for fixing - I'd hit this too!

**Comment by aaronjensen** [comment]
No problem at all. Luckily it wasn't hard for me to pinpoint. Thank you for the quick fix and the handy package.
