### ISSUE TITLE
void-function nil

### ISSUE THREAD

**Issue by shackra** [lastquestion/explain-pause-mode#88]
I believe this is something done by explain-pause. After firing treemacs, I try to expand a project directory tree and this happens:

```
Debugger entered--Lisp error: (void-function nil)
  nil(#<process Process Future<1>> "finished\n")
  apply(nil (#<process Process Future<1>> "finished\n"))
  explain--measure-function(nil (#<process Process Future<1>> "finished\n") (nil sentinel-filter treemacs-RET-action) explain-pause-log-all-process-io)
  #f(compiled-function (&rest callback-args) #<bytecode -0xdc9899ab9700487>)(#<process Process Future<1>> "finished\n")
  accept-process-output(#<process Process Future<1>>)
  pfuture-await-to-finish(#<process Process Future<1>>)
  treemacs--parse-collapsed-dirs(#<process Process Future<1>>)
  treemacs--expand-root-node(#<marker (moves after insertion) at 3 in  *Treemacs-Scoped-Buffer-#<frame emacs@sanson-gnu 0x55c56fdb7b30>*>)
  treemacs-toggle-node(nil)
  treemacs-RET-action(nil)
  funcall-interactively(treemacs-RET-action nil)
  call-interactively(treemacs-RET-action nil nil)
  command-execute(treemacs-RET-action)
```

**Comment by lastquestion** [comment]
Hi, 

I must give you honorary bug-finder :) you find all the bugs!

I think this is the same bug as #44 , which I fixed a while ago. Can you check what version / SHA commit of `explain-pause` you are on? It would be surprising if I reintroduced this bug, but possible. I also notice `explain-pause-log-all-process-io` in the call stack, which I removed in a commit a while ago, so I suspect this is an older version 🤔

**Comment by shackra** [comment]
Currently running 5398439abe1f075f43bea1dfad6c56f8412d681a

**Comment by shackra** [comment]
I've updated to whatever is current in `master` and the error is gone!
